server:
  port: 8080
logging:
  level: 
    com.singlethreadzzz.webfluxDemo: info
  file: logs/dim.log
spring:
  resources:
    static-locations: classpath:/static/
    cache:      period: 0
  data:    mongodb:      host: 127.0.0.1
      port: 27017      database: webflux
      password: webflux
      username: webflux
  mvc:
    static-path-pattern: /static/**
  banner:
    location: classpath:/static/banner/banner.txt
    